//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Students
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Student_ID { get; set; }
        public string Student_Name { get; set; }
        public string Student_IDNumber { get; set; }
        public Nullable<int> LevelID { get; set; }
        public Nullable<int> RowIID { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual Row Row { get; set; }
    }
}
